feat(asset): load asset in runtime
EIP-Pivot/pivot pull request #156
Opened 2022-05-15 08:39 UTC by Maxteke

2022-05-15 10:21 UTC, zcorniere requested changes

2022-05-15 10:21 UTC, zcorniere commented on editor/source/ImGuiCore/ImGuiManager.cxx
> +        NFD::UniquePath path;
Missing nfd initialization
```suggestion
        NFD::Guard nfd_guard;
        NFD::UniquePath path;
```

2022-05-15 16:36 UTC, Ersikan approved these changes

2022-05-16 08:25 UTC, zcorniere submitted a review, later dismissed

2022-05-16 08:27 UTC, Ersikan approved these changes

2022-05-16 08:38 UTC, merged