feat(AllocatedBuffer): allow buffer to have void type
EIP-Pivot/pivot pull request #179
Opened 2022-05-26 13:54 UTC by zcorniere

In the future Transient Ressource System, I will need to store multiple templated version of the `AllocatedBuffer`.

This PR allow a void type buffer, **that is still valid to use**, but this allow to store AllocatedBuffer into a `std::vector<AllocatedBuffer<void>>` without having issue with the Template parameters.

Also, converting between `AllocatedBuffer<void>` to `AllocatedBuffer<T>` is allowed, but not the other way around.

2022-05-28 09:59 UTC, Ersikan commented
Why not `AllocatedBuffer<std::byte>` as a default ?

2022-05-28 10:54 UTC, zcorniere commented
I thought of this too, but I think `void` carry more meaning toward "anything can be in there/we don't care what could be in there" than `std::byte`.

`AllocatedBuffer<std::byte>` is a true and valid use case of an AllocatedBuffer, whereas `AllocatedBuffer<void>` hint that we don't care what is in it and we shouldn't try to access it.

2022-05-29 09:30 UTC, Ersikan requested changes

2022-05-29 09:30 UTC, Ersikan commented on libgraphics/include/pivot/graphics/types/AllocatedBuffer.hxx
> +    auto getBytesSize() const noexcept requires(std::is_same_v<T, void>) { return getSize(); }
Use `if constexpr` to create only one method:
```suggestion
    auto getBytesSize() const noexcept requires(!std::is_same_v<T, void>) {
        if constexpr (std::is_same_v<T, void>) {
            return getSize();
        } else {
            return getSize() * sizeof(T);
        }
     }
```

2022-05-29 09:30 UTC, Ersikan commented on libgraphics/include/pivot/graphics/types/AllocatedBuffer.hxx
> +    }
Maybe do some checks that the conversion is valid or something ?

2022-05-31 09:07 UTC, Ersikan approved these changes

2022-05-31 09:07 UTC, merged